before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    - go vet
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^images:'
      - '^examples:'
scoop:
  # Template for the url which is determined by the given Token (github or gitlab)
  url_template: "http://github.com/brittonhayes/pillager/releases/{{ .Tag }}/{{ .ArtifactName }}"

  # Repository to push the app manifest to.
  bucket:
    owner: brittonhayes
    name: pillager-scoop

  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com

  # The project name and current git tag are used in the format string.
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"

  # Your app's description.
  # Default is empty.
  description: "Pillage filesystems for sensitive information"

  # Your app's license
  # Default is empty.
  license: MIT
